replicaCount: 1

image:
  repository: peter123ouob/mdb
  pullPolicy: IfNotPresent
  tag: "10008891570"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific