apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mdb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: peterdefer0822.store
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: mdb
              port:
                number: 80